### ISSUE TITLE
Impossible to use without halaxa/json-machine installed

### ISSUE THREAD

**Issue by unixslayer** [flow-php/etl-adapter-json#110]
`flow-php/etl-adapter-json` requires `halaxa/json-machine` to be installed. However, dependency is only suggested. This makes `JsonExtractor` unusable without knowlege about this dependency.

**Comment by norberttech** [comment]
hey!
there is a reason for that, I explained it on twitter recently https://twitter.com/alangbem/status/1532685699014590469?s=21&t=_PgT5rAaGS5ABswFewVIjg
One thing that is definitely missing is better installation guide in readme, I will take care of it later

**Comment by norberttech** [comment]
https://github.com/flow-php/etl-adapter-json#installation should be easier to understand it now
